# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{etvnet}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Shvets"]
  s.date = %q{2010-07-11}
  s.default_executable = %q{etvnet}
  s.description = %q{Sinatra application for ETVNet web site.}
  s.email = %q{alexander.shvets@gmail.com}
  s.executables = ["etvnet"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
     "README",
     "Rakefile",
     "VERSION",
     "bin/etvnet",
     "bin/etvnet.bat",
     "config.ru",
     "etvnet.gemspec",
     "lib/etvnet.rb",
     "lib/etvnet/app.rb",
     "lib/etvnet/media_page.rb",
     "lib/etvnet/partial.rb",
     "lib/start.rb",
     "spec/spec.opts",
     "views/display_announce_items.haml",
     "views/display_archive_items.haml",
     "views/display_browse_items.haml",
     "views/display_catalog_items.haml",
     "views/display_channel_items.haml",
     "views/display_container_items.haml",
     "views/display_items.haml",
     "views/display_media.haml",
     "views/index.haml",
     "views/layout.haml",
     "views/login.haml",
     "views/shared/_categories.haml",
     "views/shared/_category_breadcrumbs.haml",
     "views/shared/_navigation_menu.haml",
     "views/shared/_page_browser.haml",
     "views/shared/_search.haml",
     "views/shared/_see_too_items.haml",
     "views/simple_layout.haml",
     "views/stylesheet.sass"
  ]
  s.homepage = %q{http://github.com/shvets/etvnet}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Sinatra application for ETVNet web site.}
  s.test_files = [
    "spec/integration/app_test.rb",
     "spec/unit/pages_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

